source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def frameworks_pods
    pod 'CELLULAR/Locking', '~> 4.1.0'
    pod 'CELLULAR/Result', '~> 4.1.0'
    pod 'CellularLocalStorage/Core', '~> 4.1.0'
end

target 'Example' do
  platform :ios, '9.0'
  frameworks_pods
end
