source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def frameworks_pods
    pod 'CELLULAR/Locking', '~> 5.0.0'
    pod 'CellularLocalStorage/Core', :path => '../'
end

target 'Example' do
  platform :ios, '10.3'
  frameworks_pods
end
