source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def frameworks_pods
    pod 'CELLULAR/Locking', '~> 4.1.0'
    pod 'CELLULAR/Result', '~> 4.1.0'
    pod 'CellularLocalStorage/Core', :git => 'git@github.com:cellular/localstorage-swift.git', :branch => 'master'
end

target 'Example' do
  platform :ios, '9.0'
  frameworks_pods
end
