sudo: required
dist: trusty
language: generic
osx_image: xcode9.4

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success: bash <(curl -s https://codecov.io/bash)

# Build Matrix
matrix:
    include:
        # iOS
        - os: osx
          env: DESTINATION="OS=11.3,name=iPhone X"        SCHEME="CellularLocalStorage iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="CellularLocalStorage iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.3,name=iPhone 6"         SCHEME="CellularLocalStorage iOS" RUN_TESTS="YES" POD_LINT="NO"
        # watchOS
        - os: osx
          env: DESTINATION="OS=4.3,name=Apple Watch - 42mm" SCHEME="CellularLocalStorage watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="CellularLocalStorage watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CellularLocalStorage watchOS" RUN_TESTS="NO" POD_LINT="NO"
        # tvOS
        - os: osx
          env: DESTINATION="OS=11.3,name=Apple TV 4K"    SCHEME="CellularLocalStorage tvOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="CellularLocalStorage tvOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.2,name=Apple TV 1080p"  SCHEME="CellularLocalStorage tvOS" RUN_TESTS="NO" POD_LINT="NO"
